package ua.flibrary.android;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public final class CatalogDatabase extends SQLiteOpenHelper {
    private static final String DB_NAME="flibrary.db"; private static final int DB_VERSION=4; private static final char FIELD_SEPARATOR='\u001f';
    private static final String BOOK_COLUMNS="id, author, genre, title, series, series_no, file_name, extension, language, book_year, library_id, folder ";
    private static final String BOOK_KEY_SQL="CASE WHEN library_id IS NOT NULL AND library_id <> '' THEN 'id:' || library_id ELSE 'file:' || IFNULL(folder,'') || char(31) || IFNULL(file_name,'') END";
    public CatalogDatabase(Context c){super(c,DB_NAME,null,DB_VERSION);}
    @Override public void onCreate(SQLiteDatabase db){db.execSQL("CREATE TABLE books (id INTEGER PRIMARY KEY AUTOINCREMENT,author TEXT,genre TEXT,title TEXT NOT NULL,series TEXT,series_no TEXT,file_name TEXT,file_size TEXT,library_id TEXT,deleted_flag TEXT,extension TEXT,book_date TEXT,folder TEXT,language TEXT,library_rate TEXT,keywords TEXT,book_year TEXT,source_library TEXT,title_key TEXT,author_key TEXT,series_key TEXT)");createIndexes(db);createFavorites(db);createRecent(db);}
    private void createIndexes(SQLiteDatabase db){db.execSQL("CREATE INDEX IF NOT EXISTS idx_books_title ON books(title COLLATE NOCASE)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_books_author ON books(author COLLATE NOCASE)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_books_series ON books(series COLLATE NOCASE)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_books_library_id ON books(library_id)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_books_title_key ON books(title_key)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_books_author_key ON books(author_key)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_books_series_key ON books(series_key)");}
    private void createFavorites(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS favorites (book_key TEXT PRIMARY KEY, created_at INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_favorites_created ON favorites(created_at DESC)");}
    private void createRecent(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS recent_books (book_key TEXT PRIMARY KEY, opened_at INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_recent_opened ON recent_books(opened_at DESC)");}
    @Override public void onUpgrade(SQLiteDatabase db,int oldVersion,int newVersion){if(oldVersion<2){db.execSQL("ALTER TABLE books ADD COLUMN title_key TEXT");db.execSQL("ALTER TABLE books ADD COLUMN author_key TEXT");db.execSQL("ALTER TABLE books ADD COLUMN series_key TEXT");createIndexes(db);backfillSearchKeys(db);}if(oldVersion<3)createFavorites(db);if(oldVersion<4)createRecent(db);}
    private void backfillSearchKeys(SQLiteDatabase db){try(Cursor c=db.rawQuery("SELECT id,title,author,series FROM books",null)){while(c.moveToNext()){ContentValues v=new ContentValues(3);v.put("title_key",searchKey(c.getString(1)));v.put("author_key",searchKey(c.getString(2)));v.put("series_key",searchKey(c.getString(3)));db.update("books",v,"id = ?",new String[]{Long.toString(c.getLong(0))});}}}
    private static String searchKey(String v){if(v==null||v.isEmpty())return"";return Normalizer.normalize(v,Normalizer.Form.NFC).toLowerCase(Locale.ROOT).trim().replaceAll("\\s+"," ");}
    private static String bookKey(BookItem b){if(b.libraryId!=null&&!b.libraryId.isEmpty())return"id:"+b.libraryId;return"file:"+b.folder+FIELD_SEPARATOR+b.fileName;}
    public boolean isFavorite(BookItem b){try(Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM favorites WHERE book_key=? LIMIT 1",new String[]{bookKey(b)})){return c.moveToFirst();}}
    public boolean toggleFavorite(BookItem b){SQLiteDatabase db=getWritableDatabase();String k=bookKey(b);if(isFavorite(b)){db.delete("favorites","book_key=?",new String[]{k});return false;}ContentValues v=new ContentValues(2);v.put("book_key",k);v.put("created_at",System.currentTimeMillis());db.insertWithOnConflict("favorites",null,v,SQLiteDatabase.CONFLICT_REPLACE);return true;}
    public List<BookItem> listFavorites(int limit,int offset){return keyedBooks("favorites","created_at",limit,offset);}
    public void markOpened(BookItem b){ContentValues v=new ContentValues(2);v.put("book_key",bookKey(b));v.put("opened_at",System.currentTimeMillis());getWritableDatabase().insertWithOnConflict("recent_books",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    public List<BookItem> listRecent(int limit,int offset){return keyedBooks("recent_books","opened_at",limit,offset);}
    private List<BookItem> keyedBooks(String table,String timeColumn,int limit,int offset){String sql="SELECT "+BOOK_COLUMNS+"FROM books WHERE "+BOOK_KEY_SQL+" IN (SELECT book_key FROM "+table+") ORDER BY (SELECT "+timeColumn+" FROM "+table+" WHERE book_key = "+BOOK_KEY_SQL+") DESC, id LIMIT ? OFFSET ?";return queryBooks(sql,new String[]{Integer.toString(limit),Integer.toString(offset)});}
    public void beginNativeImport(){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();db.delete("books",null,null);}
    public void insertNativeBatch(String[] rows){SQLiteDatabase db=getWritableDatabase();for(String row:rows){String[] f=row.split(String.valueOf(FIELD_SEPARATOR),-1);if(f.length<17||f[2].isEmpty())continue;ContentValues v=new ContentValues(20);v.put("author",f[0]);v.put("genre",f[1]);v.put("title",f[2]);v.put("series",f[3]);v.put("series_no",f[4]);v.put("file_name",f[5]);v.put("file_size",f[6]);v.put("library_id",f[7]);v.put("deleted_flag",f[8]);v.put("extension",f[9]);v.put("book_date",f[10]);v.put("folder",f[11]);v.put("language",f[12]);v.put("library_rate",f[13]);v.put("keywords",f[14]);v.put("book_year",f[15]);v.put("source_library",f[16]);v.put("author_key",searchKey(f[0]));v.put("title_key",searchKey(f[2]));v.put("series_key",searchKey(f[3]));db.insertOrThrow("books",null,v);}}
    public void finishNativeImport(boolean success){SQLiteDatabase db=getWritableDatabase();if(!db.inTransaction())return;if(success)db.setTransactionSuccessful();db.endTransaction();}
    public long getBookCount(){try(Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM books",null)){return c.moveToFirst()?c.getLong(0):0;}}
    public List<BookItem> listBooks(int l){return listBooks(l,0);} public List<BookItem> listBooks(int l,int o){return queryBooks("SELECT "+BOOK_COLUMNS+"FROM books ORDER BY title COLLATE NOCASE,id LIMIT ? OFFSET ?",new String[]{""+l,""+o});}
    public List<BookItem> searchBooks(String q,int l){return searchBooks(q,l,0);} public List<BookItem> searchBooks(String q,int l,int o){String n="%"+searchKey(q)+"%";return queryBooks("SELECT "+BOOK_COLUMNS+"FROM books WHERE title_key LIKE ? OR author_key LIKE ? OR series_key LIKE ? ORDER BY title COLLATE NOCASE,id LIMIT ? OFFSET ?",new String[]{n,n,n,""+l,""+o});}
    public List<BookItem> booksByAuthor(String a,int l){return booksByAuthor(a,l,0);} public List<BookItem> booksByAuthor(String a,int l,int o){return queryBooks("SELECT "+BOOK_COLUMNS+"FROM books WHERE author_key=? ORDER BY title COLLATE NOCASE,id LIMIT ? OFFSET ?",new String[]{searchKey(a),""+l,""+o});}
    public List<BookItem> booksBySeries(String s,int l){return booksBySeries(s,l,0);} public List<BookItem> booksBySeries(String s,int l,int o){return queryBooks("SELECT "+BOOK_COLUMNS+"FROM books WHERE series_key=? ORDER BY CAST(series_no AS INTEGER),title COLLATE NOCASE,id LIMIT ? OFFSET ?",new String[]{searchKey(s),""+l,""+o});}
    public List<String> listAuthors(int l){return listAuthors(l,0);} public List<String> listAuthors(int l,int o){return queryNames("author",l,o);} public List<String> listSeries(int l){return listSeries(l,0);} public List<String> listSeries(int l,int o){return queryNames("series",l,o);}
    private List<String> queryNames(String col,int l,int o){ArrayList<String> r=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT "+col+",COUNT(*) FROM books WHERE "+col+" IS NOT NULL AND "+col+"<>'' GROUP BY "+col+" ORDER BY "+col+" COLLATE NOCASE LIMIT ? OFFSET ?",new String[]{""+l,""+o})){while(c.moveToNext())r.add(c.getString(0)+" ("+c.getLong(1)+")");}return r;}
    private List<BookItem> queryBooks(String sql,String[] args){ArrayList<BookItem> r=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery(sql,args)){while(c.moveToNext())r.add(new BookItem(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getString(6),c.getString(7),c.getString(8),c.getString(9),c.getString(10),c.getString(11)));}return r;}
    public List<String> search(String q,int l){ArrayList<String> r=new ArrayList<>();for(BookItem b:searchBooks(q,l)){StringBuilder s=new StringBuilder(b.title);if(!b.author.isEmpty())s.append(" — ").append(b.author);if(!b.series.isEmpty())s.append("\n  ").append(b.series);if(!b.extension.isEmpty())s.append(" [").append(b.extension).append(']');r.add(s.toString());}return r;}
}
